### ISSUE TITLE
trailingCommas should be trailingComma

### ISSUE THREAD

**Issue by doughamlin** [postlight/nodejs-typescript-kit#12]
There is a typo in the .prettierrc file. `trailingCommas` should be `trailingComma` per the [docs](https://prettier.io/docs/en/options.html#trailing-commas).

**Comment by vyzaldysanchez** [comment]
I created a PR trying to address this issue: https://github.com/postlight/nodejs-typescript-kit/pull/13

**Comment by JadTermsani** [comment]
Fixed in #13
