### ISSUE TITLE
update /starter-kit README

### ISSUE THREAD

**Issue by fdsimms** [postlight/nodejs-typescript-kit#4]
The README.md in the `/starter-kit` directory isn't up to date with the one in the root of the repo. This isn't a huge issue, but I did copy the `npx` command from `/starter-kit/README.md` and it didn't work because the repo name wasn't scoped to `@postlight/`.

**Comment by JadTermsani** [comment]
@fdsimms thanks for spotting that! Changes will be reflected in the next release

**Comment by JadTermsani** [comment]
updated in v1.0.1
