### ISSUE TITLE
add .gitignore file to outputted directory

### ISSUE THREAD

**Issue by fdsimms** [postlight/nodejs-typescript-kit#5]
It would be nice to have a `.gitignore` file by default, since many people will likely use `git` for a project built with this tool. Some sensible default directories/files would be great—the one I think would be most obviously beneficial is `node_modules`.

**Comment by JadTermsani** [comment]
Hey @fdsimms, I can't seem to reproduce this issue on Windows. I've included a `.gitignore` file in the starter kit files 

![image](https://user-images.githubusercontent.com/32297675/54524120-c8307480-4979-11e9-8ec0-0bbe4751d411.png)

**Comment by fdsimms** [comment]
hmmm interesting, here's the file structure for a freshly generated repo i made using the starter kit
<img width="300" alt="Screen Shot 2019-03-18 at 11 57 13 AM" src="https://user-images.githubusercontent.com/12575341/54544011-0d9e7300-4975-11e9-96d6-7ac72f8a4642.png">

**Comment by JadTermsani** [comment]
@fdsimms fixed in #7 and released version 1.0.1. Please test to confirm

**Comment by aortbals** [comment]
Confirmed this is fixed.
